# Generated by Django 4.0.4 on 2023-05-07 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.EmailField(blank=True, choices=[('2', 'Completed'), ('1', 'Pending'), ('3', 'Inprogress')], default='1', max_length=254, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('salary', models.CharField(blank=True, max_length=1000, null=True)),
                ('level', models.CharField(blank=True, max_length=2000, null=True)),
                ('vacancy', models.CharField(blank=True, max_length=1000, null=True)),
                ('starting', models.CharField(blank=True, max_length=1000, null=True)),
                ('duration', models.CharField(blank=True, max_length=1000, null=True)),
                ('language', models.CharField(blank=True, max_length=1000, null=True)),
                ('skill', models.CharField(blank=True, max_length=1000, null=True)),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('map', models.CharField(blank=True, max_length=1000, null=True)),
                ('overview', models.CharField(blank=True, max_length=1000, null=True)),
                ('todo', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job',
            },
        ),
    ]
